apiVersion: apps/v1
kind: Deployment
metadata:
  name: cilium-operator
  namespace: kube-system
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: cilium-operator
        env:
        - name: KUBERNETES_SERVICE_HOST
          value: "172.16.0.10"
        - name: KUBERNETES_SERVICE_PORT
          value: "6443"
      
  
