bgp:
  announce:
    loadbalancerIP: true
  enabled: true
bpf:
  hostLegacyRouting: true
  policyMapMax: 65536
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
devices: "eth+"
enableIPv4Masquerade: false
enableIdentityMark: false
externalIPs:
  enabled: true
extraConfig:
  bpf-ct-timeout-regular-any: 1h0m0s
  bpf-ct-timeout-service-any: 1h0m0s
hostPort:
  enabled: false
hubble:
  relay:
    enabled: true
    tls:
      server:
        enabled: true
    rollOutPods: true
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
  tls:
    auto:
      method: "cronJob"
k8sServiceHost: 172.16.0.10
k8sServicePort: 6443
kubeProxyReplacement: "strict"
labels: "k8s:!controller-uid k8s:!job-name k8s:!node"
loadBalancer:
  # We can't enable XDP Acceleration because rolling restart Cilium with XDP enabled disrupts in-cluster connectivity
  acceleration: disabled
  algorithm: maglev
  dsrDispatch: opt
  dsrL4Translate: backend
  mode: dsr
maglev:
  hashSeed: 3HCx6JennjWtot2U
nodePort:
  directRoutingDevice: "eth+"
  enabled: true
operator:
  rollOutPods: true
  prometheus:
    enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
policyAuditMode: false
policyEnforcementMode: "default"
prometheus:
  enabled: true
resources:
  requests:
    cpu: 100m
    memory: 400Mi
rollOutCiliumPods: true
sessionAffinity: true
socketLB:
  enabled: true
  hostNamespaceOnly: true
tunnel: "disabled"
upgradeCompatibility: "1.11"
