name: diff
description: Get diff
inputs:
  subdir:
    required: true
outputs:
  diff-count:
    value: ${{ steps.diff.outputs.diff_count }}
runs:
  using: composite
  steps:
  - uses: actions/checkout@v6
    with:
      fetch-depth: 0
  - id: diff
    name: Check diff
    shell: bash
    run: |
      COUNT=$(git diff --name-only origin/${{ github.base_ref }}..HEAD -- ${{ inputs.subdir }} | wc -l | tr -d ' ')
      echo "diff_count=${COUNT}" >> $GITHUB_OUTPUT
