apiVersion: v1
kind: Namespace
metadata:
  name: egress
  annotations:
    coil.cybozu.com/pool: egress
---
apiVersion: coil.cybozu.com/v2
kind: Egress
metadata:
  annotations:
  labels:
    app.kubernetes.io/instance: coil
  name: nat
  namespace: egress
spec:
  destinations:
  - 0.0.0.0/0
  replicas: 2
  template:
    spec:
      containers:
      - name: egress
