apiVersion: v1
data:
  config.yaml: |
    peers:
    - peer-address: 9.9.9.9
      peer-asn: 65000
      my-asn: 65001
    address-pools:
    - name: default
      protocol: bgp
      addresses:
      - 10.254.0.0/30
    - name: non-default
      protocol: bgp
      addresses:
      - 10.254.0.4/30
      auto-assign: false
kind: ConfigMap
metadata:
  name: bgp-config
  namespace: kube-system
