apiVersion: v1
kind: Pod
metadata:
  name: httpd
  namespace: default
  labels:
    name: httpd
spec:
  tolerations:
  - key: test
    operator: Exists
  nodeSelector:
    test: coil
  containers:
  - name: httpd
    image: ghcr.io/cybozu/testhttpd:0
