apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  namespace: default
  labels:
    name: ubuntu
spec:
  tolerations:
  - key: test
    operator: Exists
  nodeSelector:
    test: coil
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: name
            operator: In
            values: ["httpd"]
        topologyKey: kubernetes.io/hostname
  containers:
  - name: ubuntu
    image: ghcr.io/cybozu/ubuntu-debug:22.04
    command: ["/usr/local/bin/pause"]
