apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: coild
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: coild
          args:
            - --zap-stacktrace-level=panic
            - --enable-ipam=false
            - --enable-egress=true
