$patch: delete
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coil-ipam-controller
  namespace: kube-system
---
$patch: delete
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: coilv2-mutating-ipam-webhook-configuration
---
$patch: delete
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: coilv2-validating-ipam-webhook-configuration
