apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  ipFamily: dual
  disableDefaultCNI: true
  serviceSubnet: "10.101.0.0/16,fd00:10:0:255::/108"
nodes:
  - role: control-plane
  - role: worker
  - role: worker
  - role: worker
