
Vagrant.configure("2") do |config|
	config.vm.box = "generic/ubuntu2204"

  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.provider "hyperv" do |v|
      v.vmname = "master"
      v.memory = "2048"
      v.cpus = "1"
    end
  end

  config.vm.define "worker1" do |worker1|
    worker1.vm.hostname = "worker1"
    worker1.vm.provider "hyperv" do |v|
      v.vmname = "worker1"
      v.memory = "1024"
      v.cpus = "1"
    end
  end

  config.vm.define "worker2" do |worker2|
    worker2.vm.hostname = "worker2"
    worker2.vm.provider "hyperv" do |v|
      v.vmname = "worker2"
      v.memory = "1024"
      v.cpus = "1"
    end
  end
end
