apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-cluster-new
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-cluster-new
  template:
    metadata:
      labels:
        app: app-cluster-new
    spec:
      containers:
        - name: app
          image: nginx:latest
          ports:
            - containerPort: 80
---
# loadbalancer service
apiVersion: v1
kind: Service
metadata:
  name: app-svc-cluster-new
  namespace: test
  labels:
    lb-ipam: default-pool
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: app-cluster-new
  ports:
    - name: http
      port: 80
      targetPort: 80
