scan_timeout = 10

[character]
error_symbol = "[x](bold red)"
success_symbol = "[❯](bold green)"

[directory]
truncation_length = 3
truncate_to_repo = false
truncation_symbol = "…/"

[git_branch]

[git_commit]

[git_status]

[shell]
disabled = false

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = false
ssh_symbol = "@ "

[golang]
symbol = "Go "

[gcloud]
disabled = true

[time]
disabled = false
format = "[$time]($style) "
time_format = "%R"
utc_time_offset = "+9"
