apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: sart-controller
  name: sart-controller
  namespace: kube-system
spec:
  selector:
    matchLabels:
      control-plane: sart-controller
  template:
    spec:
      hostNetwork: true
