apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-cluster-3
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-cluster-3
  template:
    metadata:
      labels:
        app: app-cluster-3
    spec:
      containers:
        - name: app
          image: nginx:latest
          ports:
            - containerPort: 80
---
# loadbalancer service
apiVersion: v1
kind: Service
metadata:
  name: app-svc-cluster-3
  namespace: test
  labels:
    lb-ipam: default-pool
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: app-cluster-3
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-cluster-4
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-cluster-4
  template:
    metadata:
      labels:
        app: app-cluster-4
    spec:
      containers:
        - name: app
          image: nginx:latest
          ports:
            - containerPort: 80
---
# loadbalancer service
apiVersion: v1
kind: Service
metadata:
  name: app-svc-cluster-4
  namespace: test
  labels:
    lb-ipam: non-default-pool
  annotations:
    metallb.universe.tf/address-pool: non-default
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: app-cluster-4
  ports:
    - name: http
      port: 80
      targetPort: 80
