---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: test-policy
spec:
  nodeSelector:
    matchLabels:
      bgp-policy: test-policy
  virtualRouters:
  - localASN: 65001
    # exportPodCIDR: true
    serviceSelector:
      matchExpressions:
        - operator: NotIn
          key: dummy
          values:
            - dummy
    neighbors:
    - peerAddress: "9.9.9.9/32"
      peerASN: 65000
      connectRetryTimeSeconds: 120
      holdTimeSeconds: 30
      keepAliveTimeSeconds: 30
