apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-default
spec:
  selector:
    matchLabels:
      app: nginx-default
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-default
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.1
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-mars
spec:
  selector:
    matchLabels:
      app: nginx-mars
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-mars
      annotations:
        ipam.cilium.io/ip-pool: mars
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.1
        ports:
        - containerPort: 80
