apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    name: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-half-close-tester
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcp-half-close-tester
  template:
    metadata:
      labels:
        app: tcp-half-close-tester
    spec:
      containers:
        - name: app
          image: ghcr.io/terassyi/tcp-half-close-tester:0.0.2
          args:
            - server
            - -f=/data
            - -c=100
          ports:
            - containerPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-half-close-tester-interval
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcp-half-close-tester-interval
  template:
    metadata:
      labels:
        app: tcp-half-close-tester-interval
    spec:
      containers:
        - name: app
          image: ghcr.io/terassyi/tcp-half-close-tester:0.0.2
          args:
            - server
            - -f=/data
            - -c=100
            - -i=15s
          ports:
            - containerPort: 4000
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: client
  namespace: test
spec:
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: app
          image: ghcr.io/terassyi/terakoya:0.1.5
          command:
            - sleep
          args:
            - infinity
      nodeSelector:
        # cilium.io/no-schedule: "true"
        kubernetes.io/hostname: kind-worker3
      hostNetwork: true
      tolerations:
      - operator: Exists
---
apiVersion: v1
kind: Service
metadata:
  name: tcp-half-close-tester
  namespace: test
spec:
  type: NodePort
  selector:
    app: tcp-half-close-tester
  ports:
    - name: tcp
      port: 4000
      targetPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: tcp-half-close-tester-interval
  namespace: test
spec:
  type: NodePort
  selector:
    app: tcp-half-close-tester-interval
  ports:
    - name: tcp
      port: 4000
      targetPort: 4000
