apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
spec:
  selector:
    matchLabels:
      app: ubuntu-deployment
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: ubuntu-deployment
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - args:
        - pause
        image: quay.io/cybozu/ubuntu-debug:20.04
        name: ubuntu
