endpoint: 127.0.0.1:5001
channels:
  - name: coil-to-bgp
    ip_version: ipv4
    subscribers:
      - protocol: kernel
        tables:
        - 116
    publishers:
      - protocol: bgp
        endpoint: 127.0.0.1:5000
  - name: bgp-to-kernel
    ip_version: ipv4
    subscribers:
      - protocol: bgp
        endpoint: 127.0.0.1:5010
    publishers:
      - protocol: kernel
        tables:
          - 254
