resources:
  - sart.yaml
  - addresspool.yaml
  - bgp.yaml
namespace: kube-system
configMapGenerator:
  - name: sartd-fib-config
    files:
      - ./fib-config.yaml
images:
  - name: sart:dev
    # newName: ghcr.io/terassyi/sart
    # newTag: 0.0.5
    newName: sart
    newTag: dev
