apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app2
    spec:
      containers:
      - image: ghcr.io/cybozu/testhttpd:0
        name: testhttpd
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "10"]
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: app2
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app.kubernetes.io/name: app2
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 43200
