apiVersion: batch/v1
kind: CronJob
metadata:
  name: job1
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ubuntu 
            image: ghcr.io/cybozu/ubuntu:22.04
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello World
          restartPolicy: OnFailure
