---
- name: allow required ports for flannel
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  loop: "{{ cni_required_ports }}"
  when: enable_firewalld is defined and enable_firewalld|bool

- name: cni0 set to trusted zone for flannel
  firewalld:
    zone: trusted
    interface: cni0
    permanent: yes
    immediate: yes
    state: enabled
  when: enable_firewalld is defined and enable_firewalld|bool


- name: deploy flannel
  become: false
  shell: kubectl apply -f https://github.com/flannel-io/flannel/releases/download/v{{ flannel_version }}/kube-flannel.yml
  delegate_to: "{{ item }}"
  run_once: true
  loop:
  - "{{ groups.master[0] }}"


- name: wait node-ready
  import_role:
    # name: cni/wait
    name: configure_nodes/wait_node_ready 
