name: Container
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build_containers:
    strategy:
      matrix:
        job:
          - dir: "./containers/terakoya"
            container-image: terakoya
            platform: linux/amd64
          - dir: "./containers/test-server"
            container-image: test-server
            platform: linux/amd64,linux/arm64
    runs-on: ubuntu-24.04
    env:
      go-version: "1.23.4"
    steps:
      - uses: actions/checkout@v4
      - name: Check diff
        uses: ./.github/actions/diff
        id: diff
        with:
          subdir: ${{ matrix.job.dir }}
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3
        if: ${{ steps.diff.outputs.diff-count != '0' }}
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.diff.outputs.diff-count != '0' }}
      - name: Check push
        id: need-push
        run: |
          if [ "${EVENT_NAME}" != "pull_request" ]; then
            echo "PUSH=true" >> $GITHUB_OUTPUT
          else
            echo "PUSH=false" >> $GITHUB_OUTPUT
          fi
        if: ${{ steps.diff.outputs.diff-count != '0' }}
        env:
          EVENT_NAME: ${{ github.event_name }}
      - name: Get tag
        id: get-tag
        run: echo "TAG=`cat ${{ matrix.job.dir}}/TAG`" >> $GITHUB_OUTPUT
        if: ${{ steps.diff.outputs.diff-count != '0' }}
      - name: Build and Push
        uses: docker/build-push-action@v5
        if: ${{ steps.diff.outputs.diff-count != '0' }}
        with:
          context: ${{ matrix.job.dir }}
          platforms: ${{ matrix.job.platform }}
          push: ${{ steps.need-push.outputs.PUSH }}
          tags: ghcr.io/terassyi/${{ matrix.job.container-image }}:${{ steps.get-tag.outputs.TAG }}
