name: Release
on:
  push:
    tags:
      - "v*"
defaults:
  run:
    working-directory: dev
jobs:
  image:
    name: Push container image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Tag
        id: set-tag
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT # Remove "v" prefix.
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./dev
          platforms: linux/amd64
          push: true
          tags: ghcr.io/terassyi/terakoya:${{ steps.set-tag.outputs.RELEASE_TAG }}
        env:
          GO_VERSION: 1.20
